# Generated by Django 5.2 on 2025-09-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('sender_type', models.CharField(choices=[('CHARACTER', 'Character'), ('USER', 'User')], max_length=10, verbose_name='Autor wiadomości')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='npc_api.character')),
            ],
            options={
                'verbose_name': 'Wiadomość konwersacji',
                'verbose_name_plural': 'Historia konwersacji',
                'ordering': ['timestamp'],
            },
        ),
    ]
