# Generated by Django 5.2 on 2025-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_api', '0002_conversationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationhistory',
            options={'ordering': ['timestamp'], 'verbose_name': 'Conversation message', 'verbose_name_plural': 'Conversation history'},
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='message',
            field=models.TextField(verbose_name='Message content'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='sender_type',
            field=models.CharField(choices=[('CHARACTER', 'Character'), ('USER', 'User')], max_length=10, verbose_name='Message author'),
        ),
    ]
